sonarqube:
  image: my_local_sonarqube
  build: .
  ports:
    - "9000:9000"
  networks:
    - sonarnet
  environment:
    - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar
  volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
