apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: adservice-canary
spec:
  replicas: 5
  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
  selector:
    matchLabels:
      app: adservice-canary
  template:
    metadata:
      labels:
        app: adservice-canary
        istio: monitor
    spec:
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: wpatterson134/adservice:10
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
        resources:
          requests:
            cpu: 200m
            memory: 180Mi
          limits:
            cpu: 300m
            memory: 300Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          grpc:
            port: 9555
---

apiVersion: v1
kind: Service
metadata:
  name: adservice-canary
spec:
  type: ClusterIP
  selector:
    app: adservice-canary
  ports:
  - name: grpc
    port: 9555
    targetPort: 9555

